title: Matheus Arruda 
description: Portfólio de análise exploratória e visualização de dados
baseurl: "https://mtharruda.github.io/arrudamth.github.io/"
url: https://mtharruda.github.io/arrudamth.github.io/

remote_theme: piazzai/cvless  # Replace with the actual owner and repo name of the theme

# site settings
taglong: Análise exploratória e visualização de dados
tagshort: 

# author settings
author:
  name: Matheus Arruda
  email: arrudmathh@gmail.com
#photo: assets/photo.jpg
address: Sorocaba, SP, BR
phone: +55 (15) 99824-6352

# profile links
profile:
#  facebook: https://www.facebook.com/username
  github: https://github.com/mtharruda
  linkedin: https://www.linkedin.com/in/matharruda/
#  x: https://x.com/arrudamth
#  mastodon: https://mastodon.social/@username
#  bluesky: https://bsky.app/profile/username.bsky.social
  instagram: https://www.instagram.com/arrudamth/
 # xing: https://www.xing.com/profile/username
 # stackoverflow: https://stackoverflow.com/users/0000000/username
 # medium: https://medium.com/@username
  
# build settings
permalink: pretty
exclude:
  - LICENSE
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
